import jsPDF from 'jspdf';
import toast from 'react-hot-toast';

interface LeaseData {
    propertyAddress: string;
    rent: number;
    tenantId: string;
    landlordId: string;
    moveInDate: string;
}

export const generateLeaseDocument = (data: LeaseData) => {
    try {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text('RENTWISE PLATFORM', 105, 20, { align: 'center' });

        doc.setFontSize(14);
        doc.text('OFFICIAL LEASE AGREEMENT', 105, 30, { align: 'center' });

        // Line
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        // Body
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');

        const textLines = [
            `This Digital Lease Agreement (the "Agreement") is generated by RentWise algorithms`,
            `on ${new Date().toLocaleDateString()}.`,
            '',
            `PROPERTY ADDRESS:`,
            `${data.propertyAddress}`,
            '',
            `TERMS OF LEASE:`,
            `1. The Landlord (ID: ${data.landlordId.substring(0, 8)}) agrees to lease the aforementioned property.`,
            `2. The Tenant (ID: ${data.tenantId.substring(0, 8)}) agrees to pay a monthly rent of INR ${data.rent.toLocaleString('en-IN')}.`,
            `3. The official Move-In Date is recognized as ${new Date(data.moveInDate).toLocaleDateString()}.`,
            `4. Maintenance protocols dictate that the Tenant holds primary responsibility for`,
            `   upkeep standard to a RentWise certified property.`,
            '',
            `DIGITAL SIGNATURES & VERIFICATION:`,
            `This document serves as cryptographic proof of application approval through the`,
            `RentWise ecosystem. It supersedes verbal agreements.`
        ];

        let yPos = 50;
        textLines.forEach(line => {
            doc.text(line, 20, yPos);
            yPos += 7;
        });

        // Signatures
        doc.setLineWidth(0.2);
        doc.line(20, yPos + 20, 80, yPos + 20);
        doc.text('Landlord Digital Signature', 20, yPos + 27);

        doc.line(130, yPos + 20, 190, yPos + 20);
        doc.text('Tenant Digital Signature', 130, yPos + 27);

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Doc ID: RW-${Date.now()}-${Math.floor(Math.random() * 1000)} | Generated via RentWise Smart Contracts`, 105, 280, { align: 'center' });

        doc.save(`RentWise_Lease_${data.tenantId.substring(0, 5)}.pdf`);
        toast.success("Lease Agreement Matrix compiled & downloaded.");

    } catch (error) {
        toast.error("Failed to generate PDF document.");
        console.error(error);
    }
};
